name: agriculture_mobile_app
description: A mobile application for farmers with disease detection, soil analysis, and market information.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.0.4
  provider: ^6.1.1
  intl: ^0.20.2
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.1
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.5
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
